### ISSUE TITLE
Prediction for new set of premise and hypothesis pair

### ISSUE THREAD

**Issue by codehunk628** [coetaur0/ESIM#13]
I am having very hard time in understanding how to predict for a new set of premise, hypothesis pair?? #help

**Comment by coetaur0** [comment]
The usage of the model is explained in the repository README in details. I'm not sure what your issue is here exactly ? To make predictions on premise/hypothesis pairs, they need to be formatted like the test data of the SNLI or MNLI data sets and fed to the model with the [test_snli.py](https://github.com/coetaur0/ESIM/blob/master/scripts/testing/test_snli.py) or [test_mnli.py](https://github.com/coetaur0/ESIM/blob/master/scripts/testing/test_mnli.py) scripts.

**Comment by codehunk628** [comment]
that means I have to parse those hypothesis and premise sentences with some kind of parser because the snli_1.0_test file contains parsed sentences too.

**Comment by coetaur0** [comment]
Yes, out of convenience, I used in my scripts the sentences that had already been parsed in the SNLI and MNLI data sets. This means that, if you want to reuse the train or test scripts for snli or mnli, you will need to parse your data set's sentences first. This is however rather easy to do in Python. You could also simply use the [Stanford PCFG Parser](https://nlp.stanford.edu/software/lex-parser.shtml), which is what was actually used to produce the pre-parsed sentences in the SNLI and MNLI data sets.

**Comment by codehunk628** [comment]
Okay... Thank you..
