### ISSUE TITLE
when i run python3 train_snli.py, it happens

### ISSUE THREAD

**Issue by HengGeZhiZou** [coetaur0/ESIM#15]
![image](https://user-images.githubusercontent.com/24501927/111428378-60f95680-8732-11eb-89c2-a5e819168e5a.png)

pytorch:1.8.0
cuda:11.1

**Comment by coetaur0** [comment]
Apparently the issue seems to be that the data doesn't get loaded on the same device as the model. This shouldn't happen normally, since the scripts explicitly move the data on the same device as the model. Are you using a GPU to train your model ? Do you have multiple GPUs in your machine ? 
If you know the specific identifier of the GPU you are using, you could try to replace line 58 in *train_snli.py* with `device = torch.device("your_device_id")` (where `your_device_id` is replaced by the actual id, something like `cuda:0` or `cuda:1` for example). 
Please also note that this model was implemented with an older version of PyTorch (0.4), so maybe something has been broken in newer versions. The last version I tried the model on was PyTorch 1.0, and everything worked fine.

**Comment by HengGeZhiZou** [comment]
thank you, when i change the torch=1.5.1, its work
