### ISSUE TITLE
question about model parameter initialization

### ISSUE THREAD

**Issue by XingLuxi** [coetaur0/ESIM#2]
https://github.com/coetaur0/ESIM/blob/fd335c3aeb76c174e57ad79ec88397f8db8f70c4/esim/model.py#L190

as the code reference above, why initialize the parameter `bias_hh_l0[hidden_size:(2*hidden_size)]` to constant value `1.0` instead of setting all to zero ?

**Comment by coetaur0** [comment]
The values at positions `hidden_size:(2*hidden_size)`  in `bias_hh_l0` correspond to the LSTM's forget gate bias. As reported in the paper [*"An Empirical Exploration of Recurrent Network Architectures"*](http://proceedings.mlr.press/v37/jozefowicz15.pdf) by Jozefowicz et al., setting an LSTM's forget gate bias to 1 helps it avoid vanishing gradient issues and perform better, which is why this specific initialisation was applied here.

**Comment by XingLuxi** [comment]
Get it! Thanks for the detailed explanation!
