### ISSUE TITLE
Buffered data was truncated after reaching the output size limit.

### ISSUE THREAD

**Issue by zohreh3906** [coetaur0/ESIM#7]
Hi
Thanks for the implementation.
Is this code executed on Google Colab?

I ran it on Google Colab and got an error on epoch 15?

Buffered data was truncated after reaching the output size limit.

Do I need to run until epoch 64?
On which epochs will perform best?

**Comment by coetaur0** [comment]
Hi,

I haven't tried executing the code on Colab, only directly on an Nvidia GTX 1080, and never had this specific error. Note however that the code was initially run on PyTorch before the release of version 1.0, on version 0.4.1. Maybe this is an API compatibility issue.

No, you most likely won't need to run the full 64 epochs. Generally the training phase will stop around epoch 20 or so with the default parameters for early stopping, because the score usually stops improving after epoch 15.
